### ISSUE TITLE
Frame label 1 not found...

### ISSUE THREAD

**Issue by dogo21** [mathieuanthoine/PixiGAFPlayer#6]
An animation is good at GAF Player in GAF CONVERTER.
But, PixiGAFPlayer isn't working....

===================================
Uncaught 
js__$Boot_HaxeError
message
:
"Frame label 1 not found"
val
:
"Frame label 1 not found"
stack
:
"Error: Frame label 1 not found↵    at $hx_exports.GAF.GAFMovieClip.checkAndSetCurrentFrame (http://localhost:2000/first_test.js:4530:11)↵    at $hx_exports.GAF.GAFMovieClip.gotoAndPlay (http://localhost:2000/first_test.js:4299:8)↵    at $hx_exports.GAF.GAFMovieClip.runActions (http://localhost:2000/first_test.js:4495:11)↵    at $hx_exports.GAF.GAFMovieClip.changeCurrentFrame (http://localhost:2000/first_test.js:4864:8)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4327:12)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4344:24)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4344:24)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4344:24)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4344:24)↵    at $hx_exports.GAF.GAFMovieClip.advanceTime (http://localhost:2000/first_test.js:4344:24)"
__proto__
:
Error

**Comment by Hitek55** [comment]
Same problem, I use frame's label.
